// <auto-generated />
namespace CSIMediaTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataTypeTimeTaken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataTypeTimeTaken));
        
        string IMigrationMetadata.Id
        {
            get { return "201904191152303_Data-Type-TimeTaken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
